HrManagementSystem/HrManagementSystem/Controllers/ApplicantController.cs
using HrManagementSystem.CustomDataModels;
using HrManagementSystem.Models;
using Newtonsoft.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace HrManagementSystem.Controllers
{
    public class ApplicantController : Controller
    {
        BiitHrmDBEntities4 db = new BiitHrmDBEntities4();


        // GET: Applicant
        public ActionResult Applicant_Dashboard()
        {
            return View();
        }

        //--Profile
        public ActionResult Applicant_Profile()
        {
            return View();
        }
        // -- Jobs 
        public async Task<ActionResult> Applicant_JobSection(string query/*,string bestmatch*/)
        {
            ViewBag.ErrorMessage = TempData["ErrorMessage"];
            //--Education 
            var usrid = int.Parse(Session["u_id"].ToString());
            var u_edu = db.Educations.FirstOrDefault(x => x.u_id == usrid);
            //--------------
            string current_date = DateTime.Today.ToString("yyyy-MM-dd");
            DateTime parsedCurrentDate = DateTime.Parse(current_date);

            var filteredJobswithDate = db.Jobs
                .AsEnumerable() // Switch to LINQ to Objects
                .Where(x => DateTime.Parse(x.last_date_to_apply) >= parsedCurrentDate)
                .ToList();
            var filteredJobsWithQuery = db.Jobs.Where(
                x => x.title.Contains(query) || query == null && x.qualification== u_edu.degree
                ).ToList();

            var filteredJobs = (from fwd in filteredJobswithDate
                      join fwq in filteredJobsWithQuery on fwd.job_id equals fwq.job_id
                      select fwq).ToList();

            ///---Best Match with edu
            //var filteredJobsWithEdu = (from fwd in filteredJobswithDate
            //                    join fwe in u_edu on fwd.qualification equals fwe.degree
            //                    select fwd).ToList();

            return View(filteredJobs);
        }
        //--Personal Profile
        [HttpGet]
        public async Task<ActionResult> Applicant_PersonalProfile()
        {
            var usrid = int.Parse(Session["u_id"].ToString());
            var usersList = await db.Users.FirstOrDefaultAsync(x => x.u_id == usrid);

            if (usersList != null)
            {
                return View(usersList);
            }
            return RedirectToAction("Applicant_Profile");
        }

        [HttpPost]
        public async Task<ActionResult> Applicant_PersonalProfile(HttpPostedFileBase file, User model)
        {
            var user = await db.Users.FindAsync(model.u_id);
            if (user != null)
            {
                try
                {
                    // Save the uploaded file to the specified folder
                    var folder = Server.MapPath("~/Profiles/");
                    file.SaveAs(Path.Combine(folder, file.FileName.ToString()));

                    if (file != null)
                    {
                        user.f_name = model.f_name;
                        user.l_name = model.l_name;
                        user.email = model.email;
                        user.contact_no = model.contact_no;
                        user.cnic = model.cnic;
                        user.dob = model.dob;
                        user.gender = model.gender;
                        user.address = model.address;
                        user.password = model.password;
                        user.role = model.role;
                        user.image = file.FileName.ToString();

                        db.SaveChanges();

                        return RedirectToAction("Applicant_PersonalProfile");
                    }
                }
                catch (Exception)
                {
                    throw;
                }
            }
            return RedirectToAction("Applicant_Profile");
        }

        //--Education Section
        public async Task<ActionResult> Applicant_Education()
        {
            var usrid = int.Parse(Session["u_id"].ToString());
            var edu = await db.Educations.Where(x => x.u_id == usrid).ToListAsync();
            return View(edu);
        }
        //--Add Education
        public ActionResult Applicant_AddEducation()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Applicant_AddEducation(Education edu)
        {
            var usrid = int.Parse(Session["u_id"].ToString());
            edu.u_id = usrid;
            edu.has_added_edu = "true";

            db.Educations.Add(edu);
            db.SaveChanges();
            return RedirectToAction("Applicant_Education");
        }
        //--Delete Education
        public async Task<ActionResult> Delete_Education(int id)
        {

            var ed = db.Educations.Find(id);
            if (ed != null)
            {
                db.Educations.Remove(ed);
                db.SaveChanges();
                return RedirectToAction("Applicant_Education");
            }
            return RedirectToAction("Applicant_Profile");
        }
        //--Experience Section
        public async Task<ActionResult> Applicant_Experience()
        {
            var usrid = int.Parse(Session["u_id"].ToString());
            var exp = await db.Experiences.Where(x => x.u_id == usrid).ToListAsync();
            return View(exp);
        }
        //--Add Education
        public ActionResult Applicant_AddExperience()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Applicant_AddExperience(Experience exp)
        {
            var usrid = int.Parse(Session["u_id"].ToString());
            exp.u_id = usrid;
            exp.has_exp = "true";

            db.Experiences.Add(exp);
            db.SaveChanges();
            return RedirectToAction("Applicant_Experience");
        }
        //--Delete Education
        public async Task<ActionResult> Delete_Experience(int id)
        {

            var exp = db.Experiences.Find(id);
            if (exp != null)
            {
                db.Experiences.Remove(exp);
                db.SaveChanges();
                return RedirectToAction("Applicant_Experience");
            }
            return RedirectToAction("Applicant_Profile");
        }

        //--Apply Job
        public ActionResult Applicant_ApplyJob(HttpPostedFileBase file,int id)
        {
            if (id!=null)
            {
                var usrid = int.Parse(Session["u_id"].ToString());
                var userInfo = db.Users.Find(usrid);
                var job = db.Jobs.Find(id);
                try
                {
                    if (file!=null)
                    {
                        // Save the uploaded file to the specified folder
                        var folder = Server.MapPath("~/Resumes/");
                        file.SaveAs(Path.Combine(folder, file.FileName.ToString()));
                        //-Store data to db
                        JobApplication japp = new JobApplication();
                        japp.job_id= id;
                        japp.u_id=usrid;
                        //japp.name = userInfo.f_name + userInfo.l_name;
                        

                        //---Query to check best match
                        var bm= db.Educations.Where(x=>x.u_id==usrid).FirstOrDefault();
                        var jbtbl = db.Jobs.Where(x => x.job_id == id).FirstOrDefault();
                        if (bm.degree!=jbtbl.qualification )
                        {
                            japp.status = "rejected";
                        }
                        else
                        {
                            japp.status = "pending";
                        }
                        if (bm.institute=="BIMS"||bm.institute=="PRESTON"||bm.institute=="QUAID E AZAM UNIVERSITY")
                        {
                            TempData["ErrorMessage"] = "You cannot apply for this Post.";
                            return RedirectToAction("Applicant_JobSection");
                        }
                        japp.name = userInfo.f_name+" "+userInfo.l_name;
                        japp.title = job.title;
                        //--Search for committe
                        var match_cm = db.Committes.FirstOrDefault(x => x.comm_title == japp.title);
                        if (match_cm!=null)
                        {
                            JobApplicationsCommitte jac = new JobApplicationsCommitte();
                            var q = db.JobApplications.Select(x=>x).ToList();
                            var lastId = 0;
                            if (q.Count > 0)
                            {
                                lastId = q.OrderByDescending(x => x.jobapp_id).First().jobapp_id;
                            }
                            var totaln = lastId;
                            jac.jobapp_id = totaln+1;
                            jac.comm_id = match_cm.comm_id;
                            db.JobApplicationsCommittes.Add(jac);
                            db.SaveChanges();
                        }
                        japp.short_list = "false";
                        japp.doc_path = file.FileName.ToString();

                        db.JobApplications.Add(japp);
                        db.SaveChanges();
                        return RedirectToAction("Applicant_JobSection");
                    }
                }
                catch (Exception)
                {

                    throw;
                }
            }
            return View();
        }

        //--Applied Jobs
        public async Task<ActionResult> Applicant_JobApplications()
        {
            var usrid = int.Parse(Session["u_id"].ToString());

HrManagementSystem/HrManagementSystem/Views/Applicant/Applicant_AddEducation.cshtml
@model HrManagementSystem.Models.Education

@{
    ViewBag.Title = "Applicant_AddEducation";
    Layout = "~/Views/Shared/_LayoutApplicant.cshtml";
}

<body>
    <section class="vh-100">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card shadow-2-strong" style="border-radius: 1rem;">
                        <div class="card-body p-5 text-center">
                            <center>
                                @using (Html.BeginForm("Applicant_AddEducation", "Applicant", FormMethod.Post))
                                {


                                    <h3 class="mb-5">Add Education</h3>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">Degree</label>
                                        @Html.DropDownListFor(model => model.degree, new SelectList(new[]
{
 new { Value = "Matric", Text = "Matric" },
 new { Value = "Inter", Text = "Inter" },
 new { Value = "Bachelor", Text = "Bachelor" },
 new { Value = "Master", Text = "Master" }
}, "Value", "Text"), new { @class = "form-control form-control-lg" })
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">Institute</label>
                                        @Html.EditorFor(model => model.institute, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">Board</label>
                                        @Html.EditorFor(model => model.board, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">Start Date</label>
                                        @Html.EditorFor(model => model.start_date,"date", new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">End Date</label>
                                        @Html.EditorFor(model => model.end_date, "date", new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    </div>


                                    <button class="btn btn-primary btn-lg btn-block col-lg-5" type="submit">Save</button>


                                    <hr class="my-4">
                                }
                            </center>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

HrManagementSystem/HrManagementSystem/Views/Applicant/Applicant_AddExperience.cshtml
@model HrManagementSystem.Models.Experience

@{
    ViewBag.Title = "Applicant_AddExperience";
    Layout = "~/Views/Shared/_LayoutApplicant.cshtml";
}

<body>
    <section class="vh-100">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card shadow-2-strong" style="border-radius: 1rem;">
                        <div class="card-body p-5 text-center">
                            @using (Html.BeginForm("Applicant_AddExperience", "Applicant", FormMethod.Post))
                            {
                                <center>

                                    <h3 class="mb-5">Add Experience</h3>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">Company</label>
                                        @Html.EditorFor(model => model.company, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">Title</label>
                                        @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">Start Date</label>
                                        @Html.EditorFor(model => model.start_date, "date", new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">Current Work</label>
                                        @Html.EditorFor(model => model.current_work, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">End Date</label>
                                        @Html.EditorFor(model => model.end_date, "date", new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    </div>
                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">Other Skills</label>
                                        @Html.EditorFor(model => model.other_skills, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    </div>

                                    <button class="btn btn-primary btn-lg btn-block col-lg-5" type="submit">Save</button>

                                    <hr class="my-4">
                                </center>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

HrManagementSystem/HrManagementSystem/Views/Applicant/Applicant_ApplyJob.cshtml
@model HrManagementSystem.Models.JobApplication
@{
    ViewBag.Title = "Applicant_ApplyJob";
    Layout = "~/Views/Shared/_LayoutApplicant.cshtml";
}


<body>
    <section class="vh-100">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card shadow-2-strong" style="border-radius: 1rem;">
                        <div class="card-body p-5 text-center">
                            @using (Html.BeginForm("Applicant_ApplyJob", "Applicant", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                                <center>

                                    <h3 class="mb-5">Upload Your CV</h3>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">Choose File</label>
                                        <input type="file" class="form-control form-control-lg" id="file" name="file" />
                                    </div>

                                    <button class="btn btn-primary btn-lg btn-block col-lg-5" type="submit">Done</button>

                                    <hr class="my-4">
                                </center>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

HrManagementSystem/HrManagementSystem/Views/Applicant/Applicant_Dashboard.cshtml
@{
    ViewBag.Title = "Applicant_Dashboard";
    Layout = "~/Views/Shared/_LayoutApplicant.cshtml";
}

<body>
    <center>
        <br />
        <img src="~/images/jobhuntingillustration.png" class="img-fluid" />

        <form>
            <a href="@Url.Action("Applicant_JobSection","Applicant")">
                <button type="button" class="btn btn-primary btn-lg btn-block col-lg-5">Get Started</button>
            </a>
        </form>
    </center>
</body>

HrManagementSystem/HrManagementSystem/Views/Applicant/Applicant_Education.cshtml
@model List<HrManagementSystem.Models.Education>

@{
    ViewBag.Title = "Applicant_Education";
    Layout = "~/Views/Shared/_LayoutApplicant.cshtml";
}


<body>
    <br />
    <br />
    <center>
        <a class="btn btn-primary btn-lg btn-block col-lg-5" href="@Url.Action("Applicant_AddEducation","Applicant")">Add Education</a>
    </center>
    <br />
    <br />
    <table class="table">
        <thead>
            <tr class="table-primary">
                <th scope="col">Degree</th>
                <th scope="col">Institute</th>
                <th scope="col">Board</th>
                @*<th scope="col">Start Date</th>*@
                <th scope="col">Passing Year</th>
                <th scope="col"></th>
                <th scope="col"></th>

            </tr>
        </thead>
        <tbody>
            @foreach (var edu in Model)
            {
                <tr class="table-info">
                    <td>@edu.degree</td>
                    <td>@edu.institute</td>
                    <td>@edu.board</td>
                    @*<td>@edu.start_date</td>*@
                    <td>@edu.end_date</td>
                    <td>
                        <a href="@Url.Action("Delete_Education","Applicant", new { id = edu.edu_id })" class="btn btn-danger">Delete</a>
                    </td>
                    <td>
                        
                        <a href="@edu.edu_id" class="btn btn-info">&nbsp;&nbsp;Edit&nbsp;&nbsp;</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>

HrManagementSystem/HrManagementSystem/Views/Applicant/Applicant_Experience.cshtml
@model List<HrManagementSystem.Models.Experience>

@{
    ViewBag.Title = "Applicant_Experience";
    Layout = "~/Views/Shared/_LayoutApplicant.cshtml";
}


<body>
    <br />
    <br />
    <center>
        <a class="btn btn-primary btn-lg btn-block col-lg-5" href="@Url.Action("Applicant_AddExperience","Applicant")">Add Experience</a>
    </center>
    <br />
    <br />
    <table class="table">
        <thead>
            <tr class="table-primary">
                <th scope="col">Company</th>
                <th scope="col">Title</th>
                <th scope="col">Start Date</th>
                <th scope="col">Current Work</th>
                <th scope="col">End Date</th>
                <th scope="col">Other Skills</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var exp in Model)
            {
                <tr class="table-info">
                    <td>@exp.company</td>
                    <td>@exp.title</td>
                    <td>@exp.start_date</td>
                    <td>@exp.current_work</td>
                    <td>@exp.end_date</td>
                    <td>@exp.other_skills</td>
                    <td>
                        <a href="@Url.Action("Delete_Experience","Applicant", new { id = exp.exp_id })" class="btn btn-danger">Delete</a>
                    </td>
                    <td>
                        <a href="" class="btn btn-info">&nbsp;&nbsp;Edit &nbsp;&nbsp;</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>

HrManagementSystem/HrManagementSystem/Views/Applicant/Applicant_JobSection.cshtml
@model List<HrManagementSystem.Models.Job>


@{
    ViewBag.Title = "Applicant_JobSection";
    Layout = "~/Views/Shared/_LayoutApplicant.cshtml";

}
@if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
{
    <script>alert('@ViewBag.ErrorMessage');</script>
}
<body>
    <br />
    <br />
    @using (Html.BeginForm("Applicant_JobSection", "Applicant", FormMethod.Get))
    {
        <div class="input-group">
            @Html.TextBox("query", null, new { @class = "form-control", @col = "8" })
            <input type="submit" value="Search" class="btn btn-primary" />
            &nbsp;&nbsp;&nbsp;<a href="@Url.Action("Applicant_JobSection","Applicant")" class="btn btn-primary">Best Match</a>
        </div>
    }

    <br />
    <table class="table">
        <thead>
            <tr class="table-primary">
                <th scope="col">Title</th>
                <th scope="col">Qualification</th>
                <th scope="col">Salary</th>
                <th scope="col">Experience</th>
                <th scope="col">Last Date</th>
                <th scope="col">Location</th>
                <th scope="col">Total Vaccancies</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() == 0)
            {
                <tr class="table-info">
                    <td colspan="8" style="color:red">No Match Found!</td>
                </tr>
            }
            else
            {
                foreach (var job in Model)
                {
                    <tr class="table-info">
                        <td>@job.title</td>
                        <td>@job.qualification</td>
                        <td>@job.salary</td>
                        <td>@job.experience</td>
                        <td>@job.last_date_to_apply</td>
                        <td>@job.location</td>
                        <td>@job.vaccencies</td>
                        <td>
                            <a href="@Url.Action("Applicant_ApplyJob","Applicant", new { id = job.job_id })" class="btn btn-primary">Apply</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</body>

HrManagementSystem/HrManagementSystem/Views/Applicant/Applicant_PersonalProfile.cshtml
@model HrManagementSystem.Models.User

@{
    ViewBag.Title = "Applicant_PersonalProfile";
    Layout = "~/Views/Shared/_LayoutApplicant.cshtml";
}

<body>



    <section class="vh-100">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card shadow-2-strong" style="border-radius: 1rem;">
                        <div class="card-body p-5 text-center">
                            <center>
                                @using (Html.BeginForm("Applicant_PersonalProfile", "Applicant", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                {

                                    <h3 class="mb-5">Personal Info</h3>
                                    <img class="rounded-circle" src="~/Profiles/@Model.image" width="200px" height="200px" />
                                    <br />
                                    <br />
                                    <br />
                                    <div class="form-outline mb-4" hidden>
                                        @Html.HiddenFor(model => model.u_id, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">Change Image</label>
                                        <input type="file" class="form-control form-control-lg" id="file" name="file" />
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">First Name</label>
                                        @Html.EditorFor(model => model.f_name, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">Last Name</label>
                                        @Html.EditorFor(model => model.l_name, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">Email</label>
                                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">Contact No</label>
                                        @Html.EditorFor(model => model.contact_no, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">CNIC</label>
                                        @Html.EditorFor(model => model.cnic, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">DOB</label>
                                        @Html.EditorFor(model => model.dob, "date", new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                        @*<input type="date" class="form-control form-control-lg" asp-for="dob" />*@
                                    </div>
                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">Gender</label>
                                        @Html.DropDownListFor(model => model.gender, new SelectList(new[]
{
 new { Value = "Male", Text = "Male" },
 new { Value = "Female", Text = "Female" }
}, "Value", "Text"), new { @class = "form-control form-control-lg" })
                                    </div>
                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="">Address</label>
                                        @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    </div>

                                    <div class="form-outline mb-4" hidden>
                                        <label class="form-label" for="">Role</label>
                                        @Html.EditorFor(model => model.role, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    </div>

                                    <div class="form-outline mb-4" hidden>
                                        @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    </div>


                                    <button class="btn btn-primary btn-lg btn-block col-lg-5" type="submit">Update</button>

                                    <hr class="my-4">
                                }
                            </center>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

HrManagementSystem/HrManagementSystem/Views/Applicant/Applicant_Profile.cshtml
@{
    ViewBag.Title = "Applicant_Profile";
    Layout = "~/Views/Shared/_LayoutApplicant.cshtml";
}

<body>

    <div class="row">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <img src="~/images/education.jpg" class="card-img-top" />
                    <a href="@Url.Action("Applicant_Education","Applicant")" class="btn btn-primary btn-lg btn-block col-lg-5">Education</a>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <img src="~/images/personalp.jpg" class="card-img-top" />

                    <a href="@Url.Action("Applicant_PersonalProfile","Applicant")" class="btn btn-primary btn-lg btn-block col-lg-5">Personal</a>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <img src="~/images/experience.jpg" class="card-img-top" />

                    <a href="@Url.Action("Applicant_Experience","Applicant")" class="btn btn-primary btn-lg btn-block col-lg-5">Experience</a>
                </div>
            </div>
        </div>
    </div>
</body>