HrManagementSystem/HrManagementSystem/Controllers/GuardController.cs
using HrManagementSystem.CustomDataModels;
using HrManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace HrManagementSystem.Controllers
{
    public class GuardController : Controller
    {
        BiitHrmDBEntities4 db = new BiitHrmDBEntities4();
        // GET: Guard
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Guard_Dashboard(string s_query)
        {
            if (s_query!=null)
            {
                var empList = db.Users.Where(x => x.role == "employee" || x.role == "hr").ToList();
                var emp = empList.Where(x =>x.f_name.Contains(s_query)).ToList();
                return View(emp);
            }
            else
            {
                var emp = db.Users.Where(x => x.role == "employee" || x.role == "hr").ToList();
                return View(emp);
            }
        }
        //--Checking Checkin-Checkout Status
        public ActionResult Guard_CheckStatus(int id)
        {
            string current_date = DateTime.Today.ToString("yyyy-MM-dd");
            var chk = db.Attendances.FirstOrDefault(x => x.u_id == id && x.checkout=="false");        
            if (chk!=null)
            {
                int a_id = chk.att_id;
                id = a_id;
                return RedirectToAction("Guard_CheckOut/" + id);
            }
            else {
                return RedirectToAction("Guard_CheckIn/" + id);
            }
        }
        //--Checkin
        public ActionResult Guard_CheckIn(int id) 
        {
            var user = db.Users.Where(x=>x.u_id==id).ToList();
            ViewData["user_data"] = user;
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Guard_CheckIn(int id,Attendance att)
        {
            if (id!= null)
            {
                att.u_id = id;
                att.date = att.date;
                att.checkin = att.checkin;
                att.checkout = "false";
                att.status = "present";
                db.Attendances.Add(att);
                db.SaveChanges();

                return RedirectToAction("Guard_Dashboard");
            }
            else {
                return RedirectToAction("Guard_Dashboard");
            }
        }
        //--CheckOut
        public ActionResult Guard_CheckOut(int id)
        {
            var u = db.Attendances.FirstOrDefault(x => x.att_id == id);
            var user = db.Users.Where(x => x.u_id == u.u_id).ToList();
            ViewData["user_data"] = user;
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Guard_CheckOut(int id, Attendance att)
        {
            if (id != null)
            {
                var attn = db.Attendances.FirstOrDefault(x => x.att_id == id);
                attn.date = att.date;
                attn.checkout = att.checkout;
                db.SaveChanges();
                return RedirectToAction("Guard_Dashboard");
            }
            else
            {
                return RedirectToAction("Guard_Dashboard");
            }
        }
        
        public async Task<ActionResult> Guard_Profile()
        {
            var usrid = int.Parse(Session["u_id"].ToString());
            var usersList = await db.Users.FirstOrDefaultAsync(x => x.u_id == usrid);

            if (usersList != null)
            {
                return View(usersList);
            }
            return RedirectToAction("Guard_Profile");
        }
        [HttpPost]
        public async Task<ActionResult> Guard_Profile(HttpPostedFileBase file, User model)
        {
            var user = await db.Users.FindAsync(model.u_id);
            if (user != null)
            {
                try
                {
                    // Save the uploaded file to the specified folder
                    var folder = Server.MapPath("~/Profiles/");
                    file.SaveAs(Path.Combine(folder, file.FileName.ToString()));

                    if (file != null)
                    {
                        user.f_name = model.f_name;
                        user.l_name = model.l_name;
                        user.email = model.email;
                        user.contact_no = model.contact_no;
                        user.cnic = model.cnic;
                        user.dob = model.dob;
                        user.gender = model.gender;
                        user.address = model.address;
                        user.password = model.password;
                        user.role = model.role;
                        user.image = file.FileName.ToString();

                        db.SaveChanges();

                        return RedirectToAction("Guard_Profile");
                    }
                }
                catch (Exception)
                {
                    throw;
                }
            }
            return RedirectToAction("Guard_Profile");
        }

        public ActionResult Guard_AttendceReport()
        {
            var emp = db.Users.Where(x => x.role == "employee" || x.role == "hr" || x.role == "guard").ToList();
            return View(emp);
        }

        public ActionResult Guard_Report(int id)
        {
            var attR = db.Attendances.Where(x => x.u_id == id).ToList();
            return View(attR);
        }
    }
}

HrManagementSystem/HrManagementSystem/Controllers/HODController.cs
using HrManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HrManagementSystem.Controllers
{
    public class HODController : Controller
    {
        BiitHrmDBEntities4 db = new BiitHrmDBEntities4();
        // GET: HOD
        public ActionResult Hod_Dashboard()
        {
            var jobs = db.Jobs.ToList();
            return View(jobs);
        }
        public ActionResult Hod_JobApplicants(int j_id)
        {
            var jobapp = db.JobApplications.Where(x => x.job_id == j_id).ToList();
            return View(jobapp);
        }
        public ActionResult Hod_committieRemarks(int japp_id)
        {
            var jobapp = db.JobApplications.Where(x => x.jobapp_id == japp_id).ToList();
            var jremarks= db.RemarksFromCommitties.Where(x=>x.jobapp_id==japp_id).ToList();

            Session["job_app_rem_id"] = japp_id;
            

            ViewData["jobapp_info"] = jobapp;
            ViewData["remarks_info"] = jremarks;
            return View();
        }
        public ActionResult Hod_Hire()
        {
            var jid = int.Parse(Session["job_app_rem_id"].ToString());
            var hire = db.JobApplications.FirstOrDefault(x => x.jobapp_id == jid);
            if (hire != null)
            {
                hire.status = "approve";
                db.SaveChanges();
            }
            return RedirectToAction("Hod_Dashboard");
        }
        public ActionResult Hod_Reject()
        {
            var jid = int.Parse(Session["job_app_rem_id"].ToString());
            var hire = db.JobApplications.FirstOrDefault(x => x.jobapp_id == jid);
            if (hire != null)
            {
                hire.status = "rejected";
                db.SaveChanges();
            }
            return RedirectToAction("Hod_Dashboard");
        }
    }
}

HrManagementSystem/HrManagementSystem/Controllers/HrController.cs
using HrManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace HrManagementSystem.Controllers
{
    public class HrController : Controller
    {
        BiitHrmDBEntities4 db = new BiitHrmDBEntities4();
        // GET: Hr
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Hr_Dashboard()
        {
            return View();
        }
        //--Posted Jobs
        public ActionResult Hr_PostedJobs()
        {
            var pJobs = db.Jobs.ToList();
            return View(pJobs);
        }
        public ActionResult Hr_AddJobs() 
        {
            return View();
        }
        //--Add Jobs
        [HttpPost]
        public async Task<ActionResult> Hr_AddJobs(Job addJob)
        {            
            db.Jobs.Add(addJob);
            db.SaveChanges();
            return RedirectToAction("Hr_PostedJobs");
        }

        //--Hr Profile
        public async Task<ActionResult> Hr_Profile()
        {
            var usrid = int.Parse(Session["u_id"].ToString());
            var usersList = await db.Users.FirstOrDefaultAsync(x => x.u_id == usrid);

            if (usersList != null)
            {
                return View(usersList);
            }
            return RedirectToAction("Hr_Profile");
        }
        [HttpPost]
        public async Task<ActionResult> Hr_Profile(HttpPostedFileBase file, User model)
        {
            var user = await db.Users.FindAsync(model.u_id);
            if (user != null)
            {
                try
                {
                    // Save the uploaded file to the specified folder
                    var folder = Server.MapPath("~/Profiles/");
                    file.SaveAs(Path.Combine(folder, file.FileName.ToString()));

                    if (file != null)
                    {
                        user.f_name = model.f_name;
                        user.l_name = model.l_name;
                        user.email = model.email;
                        user.contact_no = model.contact_no;
                        user.cnic = model.cnic;
                        user.dob = model.dob;
                        user.gender = model.gender;
                        user.address = model.address;
                        user.password = model.password;
                        user.role = model.role;
                        user.image = file.FileName.ToString();

                        db.SaveChanges();

                        return RedirectToAction("Hr_Profile");
                    }
                }
                catch (Exception)
                {
                    throw;
                }
            }
            return RedirectToAction("Hr_Profile");
        }

        //--Attendce Report
        public ActionResult Hr_Attendce()
        {
            var emp = db.Users.Where(x => x.role == "employee" || x.role == "hr" || x.role == "guard").ToList();
            return View(emp);
        }
        public ActionResult Hr_AttendceReport(int id)
        {
            var attR = db.Attendances.Where(x => x.u_id == id).ToList();
            return View(attR);
        }
        //--Job Applications 
        public ActionResult Hr_JobApplications(string s_app)
        {
            var jobs = db.Jobs.Where(x => x.title.Contains(s_app) || s_app == null).ToList();
            return View(jobs);
        }
        //--JOb Applicants
        public ActionResult Hr_JobApplicants(int id)
        {
            var jobapp = db.JobApplications.Where(x=>x.job_id==id).ToList();
            return View(jobapp);
        }
        //--Commettie
        public ActionResult Hr_Commettie()
        {
            var c = db.Committes.ToList();
            return View(c);
        }
        //--Select Head
        public ActionResult Hr_ShowCommettieHead()
        {
            var emp = db.Users.Where(x => x.role == "employee" || x.role == "hr").ToList();
            return View(emp);
        }
        public ActionResult Hr_AddCommettie()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Hr_AddCommettie(int id,Committe cm)
        {
            Committe com = new Committe();

            com.comm_title = cm.comm_title;
            com.comm_head = id.ToString();
            db.Committes.Add(com);
            db.SaveChanges();
            return RedirectToAction("Hr_Commettie");
        }
        //---COmmettie Members
        public ActionResult Hr_CommettieMembers(int id)
        {
            if (id != null)
            {
                Session["comm_id"] = id;
            }
            var cm = db.CommitteMembers.Where(x=>x.comm_id==id).ToList();
            var usr = from m in cm
                        join u in db.Users on m.u_id equals u.u_id
                        select u;
            List<User> user = usr.ToList();
            return View(user);
        }
        public ActionResult Hr_AddCommettieMembers()
        {
            var emp = db.Users.Where(x => x.role == "employee" || x.role == "hr").ToList();
            return View(emp);
        }
        public async Task<ActionResult> Hr_AddMembers(int m_id)
        {
            CommitteMember cm = new CommitteMember();
            var c_id = int.Parse(Session["comm_id"].ToString());
            cm.comm_id = c_id;
            cm.u_id = m_id;
            db.CommitteMembers.Add(cm);
            db.SaveChanges();
            return RedirectToAction("Hr_CommettieMembers/" + c_id);
        }
        //--Leave Management
        public ActionResult Hr_LeaveApplications()
        {
            var attR = db.LeaveApplications.Where(x=>x.status=="pending").ToList();
            return View(attR);
        }
        public ActionResult Hr_laApproved(int id)
        {
            var l = db.LeaveApplications.FirstOrDefault(x => x.leaveapp_id == id);
            l.status = "approved";
            db.SaveChanges();
            return RedirectToAction("Hr_LeaveApplications");
        }
        public ActionResult Hr_laRejected(int id)
        {
            var l = db.LeaveApplications.FirstOrDefault(x => x.leaveapp_id == id);
            l.status = "reject";
            db.SaveChanges();
            return RedirectToAction("Hr_LeaveApplications");
        }
    }
}

HrManagementSystem/HrManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HrManagementSystem/HrManagementSystem/Views/Shared/_LayoutApplicant.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary">
        <div class="container">
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Applicant_Dashboard", "Applicant", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Jobs", "Applicant_JobSection", "Applicant", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Applications", "Applicant_JobApplications", "Applicant", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Profile", "Applicant_Profile", "Applicant", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Logout", "LogOut", "Users", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HrManagementSystem/HrManagementSystem/Views/Shared/_LayoutEmployee.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary">
        <div class="container">
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Employee_Dashboard", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Apply For Leave", "Employee_ApplyLeave", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Leave Applications", "Employee_LeaveApplications", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Attendce", "Employee_AttendceReport", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Commettie", "Employee_Committies", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Logout", "LogOut", "Users", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HrManagementSystem/HrManagementSystem/Views/Shared/_LayoutGuard.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary">
        <div class="container">
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Guard_Dashboard", "Guard", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Attendce", "Guard_AttendceReport", "Guard", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Profile", "Guard_Profile", "Guard", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Logout", "LogOut", "Users", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HrManagementSystem/HrManagementSystem/Views/Shared/_LayoutHod.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary">
        <div class="container">
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Hod_Dashboard", "HOD", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Logout", "LogOut", "Users", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HrManagementSystem/HrManagementSystem/Views/Shared/_LayoutHr.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary">
        <div class="container">
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Hr_Dashboard", "Hr", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Job Applications", "Hr_JobApplications", "Hr", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Add Job", "Hr_AddJobs", "Hr", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Posted Jobs", "Hr_PostedJobs", "Hr", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Leave Management", "Hr_LeaveApplications", "Hr", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Attendce Report", "Hr_Attendce", "Hr", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Commettie", "Hr_Commettie", "Hr", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Profile", "Hr_Profile", "Hr", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Logout", "LogOut", "Users", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HrManagementSystem/HrManagementSystem/Views/Shared/_LayoutUsers.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>